### ISSUE TITLE
Any tutorial for training kitti odemetry dataset?

### ISSUE THREAD

**Issue by rockywind** [basilevh/occlusions-4d#6]
Hi,
Can I used this code to training Nuscene dataset or Kitti dataset for 3D reconstruction?

**Comment by basilevh** [comment]
Hello,
In short, our method of supervision for training 3D reconstruction over time relies on switching to other camera perspectives of the same scene in order to perform dynamic scene completion, a bit like shape completion for object point clouds but then extended to entire scenes. Given one input video, the model must imagine what the scene looks like as seen from other viewpoints captured simultaneously, in order to learn about persistence of moving objects. Unfortunately, at least at the time of writing, there are no real world driving datasets with multiple viewpoints in this manner, which is why I used two synthetic datasets instead.
Hope this helps!
